export const STRINGS = {
  auth: {
    brand: "blogex",
    signInTitle: "Sign in with GitHub",
    signInSubtitle: "Use your GitHub account to continue.",
    continueWithGithub: "Continue with GitHub",
  },
  user: {
    welcome: (name: string) => `Welcome, ${name}`,
    openWorkspace: "Open Workspace",
    logout: "Log out",
  },
  createRepository: {
    toggleShow: "Create repository",
    toggleHide: "Hide repository form",
    repositoryNameLabel: "Repository name",
    repositoryNamePlaceholder: "my-new-repo",
    visibilityLabel: "Visibility",
    visibilityPublic: "Public",
    visibilityPrivate: "Private",
    creating: "Creating...",
    createRepository: "Create repository",
    openRepository: "Open repository",
    messages: {
      failedToCreateRepository: "Failed to create repository.",
      repositoryCreatedSuccessfully: "Repository created successfully.",
      requestFailedTryAgain: "Request failed. Please try again.",
    },
  },
  fileSyncStatus: {
    checking: "Checking target status",
    exists: "Exists in target repo",
    missing: "Not found in target repo",
    error: "Failed to check target status",
    unavailable: "Target status unavailable",
  },
  workspace: {
    title: "Workspace",
    settings: "Settings",
    home: "Home",
    subtitleByStep: {
      repository: "Select a repository.",
      branch: "Select a branch.",
      explorer: "Browse markdown files in _posts.",
    },
    resumeBanner: {
      message: "Existing workspace session found. Do you want to resume?",
      resume: "Resume",
      resuming: "Resuming...",
      startFresh: "Start fresh",
    },
    repositoryStep: {
      heading: "Repository",
      searchPlaceholder: "Search repositories",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      loadingRepositories: "Loading repositories...",
      noRepositoriesMatchSearch: "No repositories match your search",
      visibilityPrivate: "Private",
      visibilityPublic: "Public",
      repositoriesLoaded: (count: number) =>
        `${count} ${count === 1 ? "repository" : "repositories"} loaded.`,
      next: "Next",
      loadingBranches: "Loading branches...",
    },
    branchStep: {
      heading: "Branch",
      changeRepo: "Change repo",
      selectedRepoPrefix: "Selected:",
      searchPlaceholder: "Search branches",
      loadingBranches: "Loading branches...",
      noBranchesMatchSearch: "No branches match your search",
      connect: "Connect",
      loadingPosts: "Loading _posts...",
    },
    explorerStep: {
      changeBranch: "Change branch",
      repoAndBranch: (repo: string, branch: string) => `Repo: ${repo} | Branch: ${branch}`,
      postsHeading: "_posts",
      newPostPlaceholder: "My New Post",
      create: "Create",
      creating: "Creating...",
      searchPostsPlaceholder: "Search markdown files",
      loadingPosts: "Loading markdown files...",
      noPostsFound: "No markdown files found in _posts",
      defaultEditorName: "Markdown editor",
      closeRename: "Close rename",
      renameFilename: "Rename filename",
      comparing: "Comparing",
      compareWithTarget: "Compare with target",
      savingMarkdown: "Saving markdown",
      saveMarkdown: "Save markdown",
      edit: "Edit",
      preview: "Preview",
      editorMode: "Editor mode",
      renamePlaceholder: "new-file-name.md",
      renaming: "Renaming",
      saveFilename: "Save filename",
      cancel: "Cancel",
      compareSame: "Same",
      compareDifferent: "Different",
      compareMissingTarget: "Missing Target",
      compareMissingSource: "Missing Source",
      compareError: "Error",
      compareNotCompared: "Not Compared",
      hide: "Hide",
    },
  },
  workspaceSettings: {
    title: "Workspace Settings",
    workspace: "Workspace",
    home: "Home",
    subtitlePrefix: "Manage ",
    subtitleSuffix: " for the selected repository and branch.",
    labels: {
      repository: "Repository (owner/name)",
      branch: "Branch",
      owner: "Owner",
      targetRepo: "Target Repo",
      targetBranch: "Target Branch",
      targetDirectory: "Target Directory",
    },
    placeholders: {
      repository: "owner/repository",
      branch: "main",
      owner: "xTEddie",
      targetRepo: "owner/target-repository",
      targetBranch: "main",
      targetDirectory: "_posts",
    },
    actions: {
      loadConfig: "Load config",
      loading: "Loading...",
      saveConfig: "Save config",
      saving: "Saving...",
      syncMarkdowns: "Sync markdowns",
      loadMarkdownsToSync: "Load markdowns to sync",
      loadingMarkdowns: "Loading markdowns...",
      pullSelectedMarkdown: "Pull selected markdown",
      syncing: "Syncing...",
    },
    sync: {
      description:
        "Pull one markdown file from configured target repo into this repo's _posts directory.",
      sourceFilesHeading: "Source markdown files",
      noMarkdownFilesAvailable: "No markdown files available.",
    },
    messages: {
      setRepoAndBranchFirst: "Set repository and branch first.",
      noConfigFound: "No blogex.config.json found yet. Save to create it.",
      configurationLoaded: "Configuration loaded.",
      loadConfigFailed: "Request failed while loading config.",
      restoreSessionFailed: "Could not restore workspace session.",
      repoAndBranchRequired: "Repository and branch are required.",
      configSaved: "blogex.config.json saved.",
      saveConfigFailed: "Request failed while saving config.",
      setTargetRepoAndBranchFirst: "Set Target Repo and Target Branch first.",
      noMarkdownFilesFound: "No markdown files found.",
      loadSyncFilesFailed: "Request failed while loading sync markdown files.",
      selectOneMarkdownToSync: "Select one markdown file to sync.",
      sourceAndTargetRequired: "Source and target repo/branch values are required.",
      markdownSynced: "Markdown synced successfully.",
      syncMarkdownFailed: "Request failed while syncing markdown.",
      loading: "Loading...",
    },
  },
  workspaceFlow: {
    messages: {
      savedSessionRepoUnavailable: "Saved session repo is no longer available.",
      loadRepositoriesFailed: "Request failed while loading repositories.",
      loadBranchesFailed: "Request failed while loading branches.",
      loadMarkdownFilesFailed: "Request failed while loading markdown files.",
      loadMarkdownContentFailed: "Request failed while loading markdown content.",
      selectRepositoryFirst: "Select a repository first.",
      selectRepositoryAndBranchFirst: "Select a repository and branch first.",
      repositoryOrBranchNotSelected: "Repository or branch is not selected.",
      selectMarkdownBeforeSaving: "Select a markdown file before saving.",
      saveSuccess: "Saved successfully.",
      saveMarkdownFailed: "Request failed while saving markdown file.",
      enterTitleFirst: "Enter a title first.",
      markdownFileCreated: "Markdown file created.",
      createMarkdownFailed: "Request failed while creating markdown file.",
      selectMarkdownBeforeRenaming: "Select a markdown file before renaming.",
      enterFilenameFirst: "Enter a filename first.",
      markdownFileRenamed: "Markdown file renamed.",
      renameMarkdownFailed: "Request failed while renaming markdown file.",
      selectMarkdownBeforeComparing: "Select a markdown file before comparing.",
      targetNotConfigured:
        "Target repository is not configured. Update workspace settings first.",
      compareSame: "Source and target files are identical.",
      compareMissingTarget: "Target file does not exist yet.",
      compareMissingSource: "Source file is missing.",
      compareMarkdownFailed: "Request failed while comparing markdown files.",
    },
  },
} as const;
